# fly.toml app configuration file generated for radscheduler on 2023-10-19T14:37:38+13:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "radscheduler"
primary_region = "syd"
console_command = "bash"
swap_size_mb = 512

[build]
  dockerfile = "compose/production/django/Dockerfile"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE="config.settings.production"
  DJANGO_ACCOUNT_ALLOW_REGISTRATION="False"
  WEB_CONCURRENCY=2
  DJANGO_ALLOWED_HOSTS="*"
  DJANGO_SECURE_SSL_REDIRECT="False"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[statics]]
  guest_path = "/workspace/radscheduler/static"
  url_prefix = "/static/"